services:
  - type: web
    name: todo-app
    env: java
    buildCommand: ./mvnw clean package -DskipTests -B --no-transfer-progress
    startCommand: java -Dserver.port=8080 -Dspring.profiles.active=prod -jar target/first-0.0.1-SNAPSHOT.jar                  
    envVars:
      - key: TERM
        value: dumb
      - key: NO_COLOR
        value: "1"
      - key: SPRING_OUTPUT_ANSI_ENABLED
        value: "never"
      - key: GOOGLE_CLIENT_ID
        value: 1057612742830-9fj0qlr6lojacitk7n68rsuigj56rpcf.apps.googleusercontent.com
      - key: GOOGLE_CLIENT_SECRET
        value: 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
      - key: MONGODB_URI
        value: mongodb+srv://gaurisingh5544:gaurisingh5544@cluster0.r0s2h.mongodb.net/firstdb?retryWrites=true&w=majority
